services:
  api:
    image: ynov-docker-test-api
    build:
      context: ./ynov-docker-test-api
    ports:
      - 3333:3333
    volumes:
      - ./ynov-docker-test-api:/app
    environment:
      DB_HOST: "db"
    links:
      - "db"

  front:
    image: ynov-docker-test-front
    build:
      context: ./ynov-docker-test-front
    ports:
      - 4200:4200
    volumes:
      - ./ynov-docker-test-front:/app

  db:
    image: postgres:17.2
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: "ynov_test_password1234"
      POSTGRES_USER: "ynov_test_user"
      POSTGRES_DB: "ynov_test_db"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
